package Testing.testing_exception;

public class Main {

    public static void main(String[] args) {
        System.out.println("The application is running");
    }
}
